//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorelink.MO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentArea
    {
        public int DocId { get; set; }
        public int DocPageNo { get; set; }
        public int AreaNo { get; set; }
        public string AreaX { get; set; }
        public string AreaY { get; set; }
        public string AreaH { get; set; }
        public string AreaW { get; set; }
        public string AreaPath { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DocumentDetail DocumentDetail { get; set; }
    }
}
