//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorelink.MO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScorelinkEntities : DbContext
    {
        public ScorelinkEntities()
            : base("name=ScorelinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccTitleDict> AccTitleDicts { get; set; }
        public virtual DbSet<DocumentArea> DocumentAreas { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentInfo> DocumentInfoes { get; set; }
        public virtual DbSet<OCRResult> OCRResults { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
