//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorelink.MO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ScorelinkEntities : DbContext
    {
        public ScorelinkEntities()
            : base("name=ScorelinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccTitleDict> AccTitleDicts { get; set; }
        public virtual DbSet<DocumentArea> DocumentAreas { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentInfo> DocumentInfo { get; set; }
        public virtual DbSet<OCRResult> OCRResults { get; set; }
        public virtual DbSet<OnlineUser> OnlineUsers { get; set; }
        public virtual DbSet<StatementType> StatementTypes { get; set; }
        public virtual DbSet<SysConfig> SysConfigs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        [DbFunction("ScorelinkEntities", "F_DocumentDetail")]
        public virtual IQueryable<F_DocumentDetail_Result> F_DocumentDetail(Nullable<int> docID)
        {
            var docIDParameter = docID.HasValue ?
                new ObjectParameter("DocID", docID) :
                new ObjectParameter("DocID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_DocumentDetail_Result>("[ScorelinkEntities].[F_DocumentDetail](@DocID)", docIDParameter);
        }
    }
}
