//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorelink.MO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DocumentDetail
    {
        public int StatementId { get; set; }
        public int DocId { get; set; }
        public string StatementName { get; set; }
        public string PageNo { get; set; }
        public string FootnoteNo { get; set; }
    }
}
